<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}" @if(app()->getLocale()==='ar') dir="rtl" @endif>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Proposal</title>
    <style>
        @page { margin: 40px 36px; }
        body {
            font-family: 'dejavusans', 'DejaVu Sans', Arial, sans-serif;
            color:#111827;
        }
        @if(app()->getLocale()==='ar')
        body { direction: rtl; text-align: right; }
        .row { flex-direction: row-reverse; }
        .mr-1 { margin-right: .25rem; }
        @endif
        .header { display:flex; justify-content:space-between; align-items:flex-start; margin-bottom: 18px; }
        .title { font-size:22px; font-weight:700; }
        .muted { color:#6b7280; }
        .card { border:1px solid #e5e7eb; border-radius:8px; padding:16px; margin-bottom:14px; }
        .row { display:flex; gap:16px; }
        .col { flex:1; }
        .label { font-size:11px; color:#6b7280; text-transform:uppercase; letter-spacing:.04em; margin-bottom:4px; }
        .value { font-size:14px; font-weight:600; }
        .section-title { font-size:14px; font-weight:700; margin:18px 0 8px; }
        .small { font-size:12px; }
        .footer { margin-top: 24px; border-top:1px solid #e5e7eb; padding-top:10px; font-size:11px; color:#6b7280; }
        .qa { margin-bottom:10px; }
        .q { font-weight:600; }
    </style>
    </head>
<body>
    <div class="header">
        <div>
            <div class="title">Proposal</div>
            <div class="muted small">Project: {{ $project->title }}</div>
        </div>
        <div class="muted small">Ref: PRO-{{ $project->pid }}-{{ $bid->uid }}</div>
    </div>

    <div class="card">
        <div class="row">
            <div class="col">
                <div class="label">Client</div>
                <div class="value">{{ $client->fullname ?: $client->username }}</div>
            </div>
            <div class="col">
                <div class="label">Freelancer</div>
                <div class="value">{{ $freelancer->fullname ?: $freelancer->username }}</div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col card">
            <div class="label">Budget</div>
            <div class="value">{{ money($bid->amount, settings('currency')->code, true) }}</div>
        </div>
        <div class="col card">
            <div class="label">Timeline</div>
            <div class="value">{{ $bid->days }} {{ $bid->days == 1 ? strtolower(__('messages.t_day')) : strtolower(__('messages.t_days')) }}</div>
        </div>
    </div>

    @if($bid->message)
    <div class="card">
        <div class="section-title">Cover Message</div>
        <div class="small">{!! nl2br(e($bid->message)) !!}</div>
    </div>
    @endif

    @if($answers && count($answers))
    <div class="card">
        <div class="section-title">Questionnaire</div>
        @foreach($answers as $entry)
            <div class="qa">
                <div class="q">Q{{ ($loop->index + 1) }}. {{ $entry['question'] }}</div>
                @if(isset($entry['answer']) && $entry['answer'] !== '')
                    <div class="small">{!! nl2br(e($entry['answer'])) !!}</div>
                @else
                    <div class="small muted">No answer provided</div>
                @endif
            </div>
        @endforeach
    </div>
    @endif

    <div class="footer">Generated by {{ config('app.name') }}</div>
</body>
</html>


